package com.example.countryflags

import android.content.res.AssetManager
import android.util.JsonReader
import com.squareup.picasso.Picasso
import org.json.JSONArray
import org.json.JSONObject

class Flags_list(){
    val fileNames = mutableListOf("flag_ad.png", "flag_ae.png",
        "flag_af.png",
        "flag_ag.png",
        "flag_ai.png",
        "flag_al.png",
        "flag_am.png",
        "flag_ao.png",
        "flag_aq.png",
        "flag_ar.png",
        "flag_as.png",
        "flag_at.png",
        "flag_au.png",
        "flag_aw.png",
        "flag_ax.png",
        "flag_az.png",
        "flag_ba.png",
        "flag_bb.png",
        "flag_bd.png",
        "flag_be.png",
        "flag_bf.png",
        "flag_bg.png",
        "flag_bh.png",
        "flag_bi.png",
        "flag_bj.png",
        "flag_bl.png",
        "flag_bm.png",
        "flag_bn.png",
        "flag_bo.png",
        "flag_bq.png",
        "flag_br.png",
        "flag_bs.png",
        "flag_bt.png",
        "flag_bv.png",
        "flag_bw.png",
        "flag_by.png",
        "flag_bz.png",
        "flag_ca.png",
        "flag_cc.png",
        "flag_cd.png",
        "flag_cf.png",
        "flag_cg.png",
        "flag_ch.png",
        "flag_ci.png",
        "flag_ck.png",
        "flag_cl.png",
        "flag_cm.png",
        "flag_cn.png",
        "flag_co.png",
        "flag_cr.png",
        "flag_cu.png",
        "flag_cv.png",
        "flag_cw.png",
        "flag_cx.png",
        "flag_cy.png",
        "flag_cz.png",
        "flag_de.png",
        "flag_dj.png",
        "flag_dk.png",
        "flag_dm.png",
        "flag_do.png",
        "flag_dz.png",
        "flag_ec.png",
        "flag_ee.png",
        "flag_eg.png",
        "flag_eh.png",
        "flag_er.png",
        "flag_es.png",
        "flag_et.png",
        "flag_fi.png",
        "flag_fj.png",
        "flag_fk.png",
        "flag_fm.png",
        "flag_fo.png",
        "flag_fr.png",
        "flag_ga.png",
        "flag_gb_eng.png",
        "flag_gb_nir.png",
        "flag_gb_sct.png",
        "flag_gb_wls.png",
        "flag_gb.png",
        "flag_gd.png",
        "flag_ge.png",
        "flag_gf.png",
        "flag_gg.png",
        "flag_gh.png",
        "flag_gi.png",
        "flag_gl.png",
        "flag_gm.png",
        "flag_gn.png",
        "flag_gp.png",
        "flag_gq.png",
        "flag_gr.png",
        "flag_gs.png",
        "flag_gt.png",
        "flag_gu.png",
        "flag_gw.png",
        "flag_gy.png",
        "flag_hk.png",
        "flag_hm.png",
        "flag_hn.png",
        "flag_hr.png",
        "flag_ht.png",
        "flag_hu.png",
        "flag_id.png",
        "flag_ie.png",
        "flag_il.png",
        "flag_im.png",
        "flag_in.png",
        "flag_io.png",
        "flag_iq.png",
        "flag_ir.png",
        "flag_is.png",
        "flag_it.png",
        "flag_je.png",
        "flag_jm.png",
        "flag_jo.png",
        "flag_jp.png",
        "flag_ke.png",
        "flag_kg.png",
        "flag_kh.png",
        "flag_ki.png",
        "flag_km.png",
        "flag_kn.png",
        "flag_kp.png",
        "flag_kr.png",
        "flag_kw.png",
        "flag_ky.png",
        "flag_kz.png",
        "flag_la.png",
        "flag_lb.png",
        "flag_lc.png",
        "flag_li.png",
        "flag_lk.png",
        "flag_lr.png",
        "flag_ls.png",
        "flag_lt.png",
        "flag_lu.png",
        "flag_lv.png",
        "flag_ly.png",
        "flag_ma.png",
        "flag_mc.png",
        "flag_md.png",
        "flag_me.png",
        "flag_mf.png",
        "flag_mg.png",
        "flag_mh.png",
        "flag_mk.png",
        "flag_ml.png",
        "flag_mm.png",
        "flag_mn.png",
        "flag_mo.png",
        "flag_mp.png",
        "flag_mq.png",
        "flag_mr.png",
        "flag_ms.png",
        "flag_mt.png",
        "flag_mu.png",
        "flag_mv.png",
        "flag_mw.png",
        "flag_mx.png",
        "flag_my.png",
        "flag_mz.png",
        "flag_na.png",
        "flag_nc.png",
        "flag_ne.png",
        "flag_nf.png",
        "flag_ng.png",
        "flag_ni.png",
        "flag_nl.png",
        "flag_no.png",
        "flag_np.png",
        "flag_nr.png",
        "flag_nu.png",
        "flag_nz.png",
        "flag_om.png",
        "flag_pa.png",
        "flag_pe.png",
        "flag_pf.png",
        "flag_pg.png",
        "flag_ph.png",
        "flag_pk.png",
        "flag_pl.png",
        "flag_pm.png",
        "flag_pn.png",
        "flag_pr.png",
        "flag_ps.png",
        "flag_pt.png",
        "flag_pw.png",
        "flag_py.png",
        "flag_qa.png",
        "flag_re.png",
        "flag_ro.png",
        "flag_rs.png",
        "flag_ru.png",
        "flag_rw.png",
        "flag_sa.png",
        "flag_sb.png",
        "flag_sc.png",
        "flag_sd.png",
        "flag_se.png",
        "flag_sg.png",
        "flag_sh.png",
        "flag_si.png",
        "flag_sj.png",
        "flag_sk.png",
        "flag_sl.png",
        "flag_sm.png",
        "flag_sn.png",
        "flag_so.png",
        "flag_sr.png",
        "flag_ss.png",
        "flag_st.png",
        "flag_sv.png",
        "flag_sx.png",
        "flag_sy.png",
        "flag_sz.png",
        "flag_tc.png",
        "flag_td.png",
        "flag_tf.png",
        "flag_tg.png",
        "flag_th.png",
        "flag_tj.png",
        "flag_tk.png",
        "flag_tl.png",
        "flag_tm.png",
        "flag_tn.png",
        "flag_to.png",
        "flag_tr.png",
        "flag_tt.png",
        "flag_tv.png",
        "flag_tw.png",
        "flag_tz.png",
        "flag_ua.png",
        "flag_ug.png",
        "flag_um.png",
        "flag_us.png",
        "flag_uy.png",
        "flag_uz.png",
        "flag_va.png",
        "flag_vc.png",
        "flag_ve.png",
        "flag_vg.png",
        "flag_vi.png",
        "flag_vn.png",
        "flag_vu.png",
        "flag_wf.png",
        "flag_ws.png",
        "flag_xk.png",
        "flag_ye.png",
        "flag_yt.png",
        "flag_za.png",
        "flag_zm.png",
        "flag_zw.png"
        )
    val countryNames = mutableListOf("Andorra",
        "United Arab Emirates",
        "Afghanistan",
        "Antiguaand Barbuda",
        "Anguilla",
        "Albania",
        "Armenia",
        "Angola",
        "Antarctica",
        "Argentina",
        "American Samoa",
        "Austria",
        "Australia",
        "Aruba",
        "ÅlandIslands",
        "Azerbaijan",
        "Bosniaand Herzegovina",
        "Barbados",
        "Bangladesh",
        "Belgium",
        "BurkinaFaso",
        "Bulgaria",
        "Bahrain",
        "Burundi",
        "Benin",
        "Saint Barthélemy",
        "Bermuda",
        "Brunei",
        "Bolivia",
        "Caribbean Netherlands",
        "Brazil",
        "Bahamas",
        "Bhutan",
        "Bouvet Island",
        "Botswana",
        "Belarus",
        "Belize",
        "Canada",
        "Cocos(Keeling) Islands",
        "DRCongo",
        "Central African Republic",
        "Republicofthe Congo",
        "Switzerland",
        "Côted'Ivoire (IvoryCoast)",
        "CookIslands",
        "Chile",
        "Cameroon",
        "China",
        "Colombia",
        "Costa Rica",
        "Cuba",
        "Cape Verde",
        "Curaçao",
        "Christmas Island",
        "Cyprus",
        "Czechia",
        "Germany",
        "Djibouti",
        "Denmark",
        "Dominica",
        "Dominican Republic",
        "Algeria",
        "Ecuador",
        "Estonia",
        "Egypt",
        "Western Sahara",
        "Eritrea",
        "Spain",
        "Ethiopia",
        "Finland",
        "Fiji",
        "Falkland Islands",
        "Micronesia",
        "Faroe Islands",
        "France",
        "Gabon",
        "Eland",
        "Northern Ireland",
        "Scotland",
        "Wales",
        "United Kingdom",
        "Grenada",
        "Georgia",
        "French Guiana",
        "Guernsey",
        "Ghana",
        "Gibraltar",
        "Greenland",
        "Gambia",
        "Guinea",
        "Guadeloupe",
        "Equatorial Guinea",
        "Greece",
        "SouthGeorgia",
        "Guatemala",
        "Guam",
        "Guinea-Bissau",
        "Guyana",
        "HongKong",
        "Heard Islandand McDonald Islands",
        "Honduras",
        "Croatia",
        "Haiti",
        "Hungary",
        "Indonesia",
        "Ireland",
        "Israel",
        "Isleof Man",
        "India",
        "British Indian Ocean Territory",
        "Iraq",
        "Iran",
        "Iceland",
        "Italy",
        "Jersey",
        "Jamaica",
        "Jordan",
        "Japan",
        "Kenya",
        "Kyrgyzstan",
        "Cambodia",
        "Kiribati",
        "Comoros",
        "Saint Kittsand Nevis",
        "NorthKorea",
        "SouthKorea",
        "Kuwait",
        "Cayman Islands",
        "Kazakhstan",
        "Laos",
        "Lebanon",
        "SaintLucia",
        "Liechtenstein",
        "SriLanka",
        "Liberia",
        "Lesotho",
        "Lithuania",
        "Luxembourg",
        "Latvia",
        "Libya",
        "Morocco",
        "Monaco",
        "Moldova",
        "Montenegro",
        "SaintMartin",
        "Madagascar",
        "MarshallIslands",
        "North Macedonia",
        "Mali",
        "Myanmar",
        "Mongolia",
        "Macau",
        "Northern Mariana Islands",
        "Martinique",
        "Mauritania",
        "Montserrat",
        "Malta",
        "Mauritius",
        "Maldives",
        "Malawi",
        "Mexico",
        "Malaysia",
        "Mozambique",
        "Namibia",
        "NewCaledonia",
        "Niger",
        "NorfolkIsland",
        "Nigeria",
        "Nicaragua",
        "Netherlands",
        "Norway",
        "Nepal",
        "Nauru",
        "Niue",
        "New Zealand",
        "Oman",
        "Panama",
        "Peru",
        "French Polynesia",
        "Papua NewGuinea",
        "Philippines",
        "Pakistan",
        "Poland",
        "Saint Pierreand Miquelon",
        "Pitcairn Islands",
        "Puerto Rico",
        "Palestine",
        "Portugal",
        "Palau",
        "Paraguay",
        "Qatar",
        "Réunion",
        "Romania",
        "Serbia",
        "Russia",
        "Rwanda",
        "Saudi Arabia",
        "Solomon Islands",
        "Seychelles",
        "Sudan",
        "Sweden",
        "Singapore",
        "Saint Helena,Ascensionand Tristanda Cunha",
        "Slovenia",
        "Svalbardand Jan Mayen",
        "Slovakia",
        "Sierra Leone",
        "San Marino",
        "Senegal",
        "Somalia",
        "Suriname",
        "SouthSudan",
        "São Toméand Príncipe",
        "El Salvador",
        "Sint Maarten",
        "Syria",
        "Eswatini(Swaziland)",
        "Turksand CaicosIslands",
        "Chad",
        "French Southernand Antarctic Lands",
        "Togo",
        "Thailand",
        "Tajikistan",
        "Tokelau",
        "Timor-Leste",
        "Turkmenistan",
        "Tunisia",
        "Tonga",
        "Turkey",
        "Trinidadand Tobago",
        "Tuvalu",
        "Taiwan",
        "Tanzania",
        "Ukraine",
        "Uganda",
        "United States Minor Outlying Islands",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vatican City(HolySee)",
        "Saint Vincentandthe Grenadines",
        "Venezuela",
        "British Virgin Islands",
        "UnitedS tates Virgin Islands",
        "Vietnam",
        "Vanuatu",
        "Wallisand Futuna",
        "Samoa",
        "Kosovo",
        "Yemen",
        "Mayotte",
        "South Africa",
        "Zambia",
        "Zimbabwe"
    )
    var mapFlags_list = mutableMapOf<String, String>().put(fileNames.toString(),
        countryNames.toString()
    )

    fun checkList(){
        println(mapFlags_list?.get(0))
        println(mapFlags_list?.get(1))
        println(mapFlags_list?.get(2))

    }


}

